### ISSUE TITLE
When you spend all your money, the Money Counter goes blank.

### ISSUE THREAD

**Issue by ransell** [leodenault/fashion#42]
I had $20.
I spent it on 2 accessories.
The counter did not show $0, it was simply blank.
When I battled (and won) against the Mecha Catgirl Shopper, I won $9, but it did not show up in the Money Counter. It remained blank.

**Comment by leodenault** [comment]
I can't seem to replicate this bug. :( Does it still happen for you?

**Comment by leodenault** [comment]
Found this happening on the 4th floor because the money count isn't the same component as the rest in all the other scenes.
