### ISSUE TITLE
Cannot scroll left or right on Floor 2

### ISSUE THREAD

**Issue by ransell** [leodenault/fashion#9]
Start on Floor 1, you can "scroll" right with the right arrow key. When you click the escalator to go up, you come to Floor 2. You cannot "scroll" right _or_ left with the right arrow key. When you click the escalator to go back down to Floor 1, you can still scroll on that floor.

**Comment by leodenault** [comment]
Figured that out earlier tonight. Thought I hadn't pushed the bug to the server, but apparently did. Will push the local fix ASAP.

**Comment by ransell** [comment]
GO TO SLEEP
